source:
  type: datahub-business-glossary
  config:
    # Coordinates
    file: transdev-businessglossary.yml
    enable_auto_id: true # recommended to set to true so datahub will auto-generate guids from your term names
